---
language: node_js
node_js: "9"
services:
  - mongodb
  - docker
notifications:
  email: false
before_script:
  - sleep 15
  - mongo growler --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm test
after_success:
  - npm i -g coveralls codeclimate-test-reporter
  - coveralls < coverage/lcov.info
  - codeclimate-test-reporter < coverage/lcov.info
before_deploy:
  - npm install -g cli-engine-config cli-engine-command heroku-cli
  - heroku plugins:install heroku-container-registry --force
  - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
deploy:
  provider: script
  script: heroku container:push web --app api-growlerapp
  skip_cleanup: true
  on:
    branch: master
