language: node_js
cache:
  directories:
    - ~/.npm
    - .nyc_output
node_js:
  - "11"
notifications:
  email: false
stages:
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: lint
      name: eslint
      script: npx eslint .
    - stage: test
      services:
        - mongodb
        - docker
      before_script:
        - sleep 15
        - mongo growler --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
      script: npm t
      after_success:
        - npm i -g coveralls codeclimate-test-reporter
        - coveralls < coverage/lcov.info
        - codeclimate-test-reporter < coverage/lcov.info
    - stage: deploy
      name: production
      before_script:
        - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
        - docker build -t registry.heroku.com/api-growlerapp/web --build-arg NODE_ENV=production .
      script:
        - |
          docker push registry.heroku.com/api-growlerapp/web
          IMAGE_ID=$(docker inspect registry.heroku.com/api-growlerapp/web --format={{.Id}})
          PAYLOAD='{"updates":[{"type":"web","docker_image":"'"$IMAGE_ID"'"}]}'
          curl -n -X PATCH https://api.heroku.com/apps/api-growlerapp/formation \
          -d "$PAYLOAD" \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"
      skip_cleanup: true
      if: branch = master
    - stage: deploy
      name: testing
      before_script:
        - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
        - docker build -t registry.heroku.com/api-growlerapp-dev/web --build-arg NODE_ENV=production .
      script:
        - |
          docker push registry.heroku.com/api-growlerapp-dev/web
          IMAGE_ID=$(docker inspect registry.heroku.com/api-growlerapp-dev/web --format={{.Id}})
          PAYLOAD='{"updates":[{"type":"web","docker_image":"'"$IMAGE_ID"'"}]}'
          curl -n -X PATCH https://api.heroku.com/apps/api-growlerapp-dev/formation \
          -d "$PAYLOAD" \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"
      skip_cleanup: true
      if: branch != master
