---
version: '3'

services:
  app:
    build: .
    env_file: .env
    environment:
      MONGODB_URI: mongodb://mongo/growler_test
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: npm run test:docker
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.7.9
    volumes:
      - mongo:/data/db

volumes:
  mongo:
