---
version: '3'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file: .env
    environment:
      NODE_ENV: production
      PLAYGROUND: "true"
      MONGODB_URI: mongodb://mongo/growler
    ports:
      - 3000:3000
  mongo:
    image: mongo:3.6.3
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

volumes:
  mongo:
