---
version: '3'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file: .env
    environment:
      NODE_ENV: production
      PLAYGROUND: "true"
      MONGODB_URI: mongodb://mongo/growler
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.7.9
    volumes:
      - mongo:/data/db

volumes:
  mongo:
